### ISSUE TITLE
Moderation: json body could not be decoded: invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by Banonevar** [dlive-apis/dlivetv-api-js#10]
**Describe the bug**
Trying to use `dlive.client.moderation.deleteMessage(object.id).then(console.log).catch(console.log)`
Where object.id it's message id from chat, and it's return me error:
```
Error: json body could not be decoded: invalid character 'e' looking for beginning of value
    at webRequest.then (\node_modules\dlivetv-unofficial-api\src\dliveModeration.js:29:54)
```

**To Reproduce**
Possible use same as me

**Expected behavior**
Should delete message from chat

**Screenshots**

**Development runtime (please complete the following information):**
- dlive 2.1.18
**Additional context**

**Comment by Carbowix** [comment]
It's currently unknown why this issue is currently being produced. I'll continue to investigate and notify you if it's solved

**Comment by Carbowix** [comment]
Issue should be resolved in the next hotfix
