### ISSUE TITLE
getChannelTopContributors: TypeError: Cannot read property 'topContributions' of undefined

### ISSUE THREAD

**Issue by Banonevar** [dlive-apis/dlivetv-api-js#13]
**Describe the bug**
getChannelTopContributors function throw some error
```
TypeError: Cannot read property 'topContributions' of undefined
    at webRequest.then (D:\Projects\node_modules\dlivetv-unofficial-api\src\util.js:169:76)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**To Reproduce**
I used 
```javascript
getChannelTopContributors(config.dlive.displayname, 3, 'ALL_TIME').then(console.log).catch(console.log)
```

**Expected behavior**
Should return Contributors

**Screenshots**

**Development runtime (please complete the following information):**
- dlive 2.1.18

**Additional context**

**Comment by Carbowix** [comment]
Issue was fixed with 2.1.19, now published. Please update your npm package
