### ISSUE TITLE
getChannelFollowers return length of array instead of actuall array

### ISSUE THREAD

**Issue by Banonevar** [dlive-apis/dlivetv-api-js#7]
**Describe the bug**
When i use `getChannelFollowers()` function it's just return `5` or whatever number i typed in function argument

**To Reproduce**
use 
```javascript
getChannelFollowers(config.dlive.displayname, 5).then(console.log).catch(console.log)
```

**Expected behavior**
Should return an array of followers

**Screenshots**

**Development runtime (please complete the following information):**
 - OS: Win 10 
 - node v11.13.0

**Additional context**

**Comment by Banonevar** [comment]
https://github.com/dlive-apis/dlivetv-api-js/blob/master/src/util.js#L96

**Comment by Carbowix** [comment]
We are sorry for inconvenience, the issue will be fixed tomorrow.
