### ISSUE TITLE
Cannot find module 'dlivetv-unofficial-api'

### ISSUE THREAD

**Issue by Banonevar** [dlive-apis/dlivetv-api-js#8]
**Describe the bug**
```
babel-node app.js

internal/modules/cjs/loader.js:657
    throw err;
    ^

Error: Cannot find module 'dlivetv-unofficial-api'
```
i tryed `npm i dlivetv-unofficial-api` and `yarn add dlivetv-unofficial-api`, both download package w/o `src` folder
**To Reproduce**
`npm i dlivetv-unofficial-api` or `yarn add dlivetv-unofficial-api`

**Expected behavior**
Should install correct

**Screenshots**
![img](https://i.imgur.com/lreDXp3.png)

**Development runtime (please complete the following information):**
 - OS: win 10
 - Node & NPM version: 11.3.0, 6.7.0

**Additional context**

**Comment by timedotcc** [comment]
Release revoked. Please update once and wait until @Carbowix releases the new version.
