### ISSUE TITLE
Uptime, Stats

### ISSUE THREAD

**Issue by ic3dr460n** [dlive-apis/dlivetv-api-js#9]
Was curious if API could allow for getting a streams uptime and viewer statistics. I know theres no viewer list, but would there be a way of tracking follow age/hours in stream?

**Comment by timedotcc** [comment]
I honestly have no idea how to do that.

**Comment by ic3dr460n** [comment]
Lol, that's okay. Was a long shot but was trying to figure it out. If the capability isn't there you can close this. :)

**Comment by Burnett01** [comment]
Sorry I'm unable to assist you here, @timedotcc 
Pretty jammed with projects and getting the C-Core finished.

**Comment by timedotcc** [comment]
I think it will be implemented in the future. It is reserved for version 3.0.0.
